# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-10 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(max_length=200)),
                ('loser', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(verbose_name='created_on')),
                ('modified_on', models.DateTimeField(verbose_name='modified_on')),
            ],
        ),
        migrations.CreateModel(
            name='Rankings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('ranking', models.IntegerField(default=1000)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_on', models.DateTimeField(verbose_name='start_on')),
                ('season_number', models.IntegerField(default=1)),
                ('end_on', models.DateTimeField(null=True, verbose_name='end_on')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
