# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoublesGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(verbose_name='created_on')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_1', models.CharField(max_length=200)),
                ('player_2', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200, null=True, unique=True)),
                ('ranking', models.IntegerField(default=1000)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='doublesgame',
            name='losing_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='losing_team', to='history.Teams', to_field='name'),
        ),
        migrations.AddField(
            model_name='doublesgame',
            name='winning_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winning_team', to='history.Teams', to_field='name'),
        ),
    ]
