# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-05 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20190723_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(verbose_name='created_on')),
                ('requester', models.CharField(max_length=200)),
                ('log_message', models.TextField()),
                ('slack_link', models.URLField()),
            ],
        ),
    ]
